<#
.SYNOPSIS
    One-time setup: registers LexChat as a Task Scheduler task that starts at boot.

.DESCRIPTION
    Run this once as Administrator after git pull on the target server.
    It detects the Python and Ollama executable paths (while you are logged in and
    PATH is available), writes them to autostart_config.ps1, then registers a
    "LexChat Autostart" task that calls start_background.ps1 at every system boot
    as the SYSTEM account — no login required.

.EXAMPLE
    # In an elevated PowerShell session:
    cd C:\Projects\LexChat
    .\deployment\install_autostart.ps1
#>

#Requires -RunAsAdministrator

$ErrorActionPreference = "Stop"
$scriptDir  = $PSScriptRoot
$repoRoot   = (Resolve-Path "$scriptDir\..").Path
$startScript = "$scriptDir\start_background.ps1"
$configFile  = "$scriptDir\autostart_config.ps1"
$logsDir     = "$scriptDir\logs"
$taskName    = "LexChat Autostart"

Write-Host ""
Write-Host "=== LexChat Autostart Installer ==="
Write-Host ""

# Create logs directory
if (-not (Test-Path $logsDir)) {
    New-Item -ItemType Directory -Path $logsDir | Out-Null
    Write-Host "Created logs directory: $logsDir"
}

# --- Detect Python ---
$venvPy = "$repoRoot\server_py\venv\Scripts\python.exe"
if (Test-Path $venvPy) {
    $pythonExe = $venvPy
    Write-Host "Python : $pythonExe  (venv)"
} else {
    $pythonCmd = Get-Command python -ErrorAction SilentlyContinue
    if ($pythonCmd) {
        $pythonExe = $pythonCmd.Source
        Write-Host "Python : $pythonExe  (system)"
    } else {
        Write-Error "Python not found in PATH and no venv at $venvPy. Install Python and re-run."
        exit 1
    }
}

# --- Detect Ollama ---
$ollamaExe = $null
$ollamaService = Get-Service -Name "Ollama" -ErrorAction SilentlyContinue
if ($ollamaService) {
    Write-Host "Ollama : Windows service 'Ollama' found — no path needed."
} else {
    # Try PATH
    $ollamaCmd = Get-Command ollama -ErrorAction SilentlyContinue
    if ($ollamaCmd) {
        $ollamaExe = $ollamaCmd.Source
    } else {
        # Scan all user profile directories for a per-user Ollama install
        $userDirs = Get-ChildItem "C:\Users" -Directory -ErrorAction SilentlyContinue
        foreach ($dir in $userDirs) {
            $candidate = "$($dir.FullName)\AppData\Local\Programs\Ollama\ollama.exe"
            if (Test-Path $candidate) {
                $ollamaExe = $candidate
                break
            }
        }
    }

    if ($ollamaExe) {
        Write-Host "Ollama : $ollamaExe"
    } else {
        Write-Warning "Ollama executable not found. The autostart task will skip starting Ollama."
        Write-Warning "If Ollama is needed, install it and re-run this script."
    }
}

# --- Write autostart_config.ps1 ---
$ollamaValue = if ($ollamaExe) { "`"$ollamaExe`"" } else { "`$null" }
$configContent = @"
# Generated by install_autostart.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Do not edit manually — re-run install_autostart.ps1 to regenerate.
`$LEXCHAT_PYTHON = "$pythonExe"
`$LEXCHAT_OLLAMA = $ollamaValue
"@
$configContent | Set-Content -Path $configFile -Encoding UTF8
Write-Host "Config written: $configFile"

# --- Register Task Scheduler task ---
$action = New-ScheduledTaskAction `
    -Execute  "powershell.exe" `
    -Argument "-NonInteractive -NoProfile -ExecutionPolicy Bypass -File `"$startScript`""

$trigger = New-ScheduledTaskTrigger -AtStartup

# StartWhenAvailable: run the task even if the trigger was missed (e.g. was powered off).
# ExecutionTimeLimit: the launcher script itself exits in seconds; cap at 5 min for safety.
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::FromMinutes(5))

$principal = New-ScheduledTaskPrincipal `
    -UserId   "SYSTEM" `
    -LogonType ServiceAccount `
    -RunLevel Highest

# Remove any existing registration before re-registering
$existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if ($existing) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    Write-Host "Removed existing '$taskName' task."
}

Register-ScheduledTask `
    -TaskName   $taskName `
    -Action     $action `
    -Trigger    $trigger `
    -Settings   $settings `
    -Principal  $principal `
    -Description "Starts LexChat (Ollama + FastAPI backend) at system boot without requiring a login." `
    | Out-Null

Write-Host ""
Write-Host "Task '$taskName' registered successfully."
Write-Host ""
Write-Host "LexChat will now start automatically on every system boot."
Write-Host ""
Write-Host "To start immediately without rebooting:"
Write-Host "  Start-ScheduledTask -TaskName '$taskName'"
Write-Host ""
Write-Host "To tail startup and backend logs:"
Write-Host "  Get-Content '$logsDir\startup.log' -Wait"
Write-Host "  Get-Content '$logsDir\backend.log'  -Wait"
Write-Host ""
Write-Host "To manage via GUI: open Task Scheduler (taskschd.msc) and look for '$taskName'."
Write-Host ""
